### ISSUE TITLE
泰坦之旅 tqeditor.apk

### ISSUE THREAD

**Issue by wuwujia** [derron/TQEditor#1]
有没有说明文档啊？

**Comment by Zworlds** [comment]
没有------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Fernando&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月31日(星期天) 上午10:12
收件人:&nbsp;&quot;derron/TQEditor&quot;<TQEditor@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[derron/TQEditor] 泰坦之旅 tqeditor.apk (#1)

**Comment by wuwujia** [comment]
自己摸索已经会用了。

**Comment by derron** [comment]
> 自己摸索已经会用了。

@wuwujia 方便的话，提交一个PR补充一个文档，这样更多的人也会用了。
